Repository Satellite-im/testing-uplink, pull requests merged in 2023-11, with the labels that each got.

#516 chore(appium): use nutjs library instead of robotjs
  package-lock.json
  package.json
  tests/helpers/commands.ts
  tests/screenobjects/AppScreen.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
Labels: Missing dev review

#518 chore(appium): update dependencies for webdriverio
  package-lock.json
  package.json
Labels: Missing dev review

#520 chore(appium): update toolchain to build uplink
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#523 chore(typo): fix typo
  tests/specs/06-settings-general.spec.ts
Labels: Missing dev review

#522 chore(docs): minor suggestions
  docs/TEST_COVERAGE.md
Labels: Missing dev review

#521 chore(docs): minor suggestions
  README.md
Labels: Missing dev review

#525 test(update): increase timeout on large file uploads
  tests/screenobjects/files/FilesScreen.ts
  tests/specs/03-files.spec.ts
Labels: Missing dev review

#524 chore(update): minor update
  tests/specs/06-settings-general.spec.ts
Labels: Missing dev review

#424 chore(appium): multiremote mac attempt on latest macos ci
  .github/workflows/ui-automated-tests.yml
  README.md
  config/wdio.mac.multiremote.conf.ts
  config/wdio.windows.multiremote.conf.ts
  tests/helpers/commands.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/screenobjects/chats/EmojiSelector.ts
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
  tests/specs/reusable-accounts/06-chat-topbar.spec.ts
  tests/specs/reusable-accounts/07-quick-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/specs/reusable-accounts/11-group-chats-sidebar.spec.ts
  tests/specs/scripts/01-multiple-logins.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
  tests/suites/Chats/02-Empty.suite.ts
Labels: Missing dev review, Draft

#526 test(update): remove hover on emoji button input bar
  tests/screenobjects/chats/InputBar.ts
Labels: Missing dev review, Failed Automated Test

#527 screenobject(update): ammend my error on ui locator
  tests/screenobjects/chats/InputBar.ts
Labels: Missing dev review

#528 test(update): fixing chats test first set
  tests/screenobjects/chats/ContextMenu.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/ReplyPrompt.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#529 chore(appium): remove windows chat from CI
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#530 test(update): fixing topbar and quick profile chats tests
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/chats/PinnedMessages.ts
  tests/screenobjects/chats/Topbar.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/06-chat-topbar.spec.ts
  tests/specs/reusable-accounts/07-quick-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#531 test(update): minor improvements to tests failing on CI but not locally
  config/wdio.mac.multiremote.conf.ts
  tests/helpers/commands.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/03-files.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review, Failed Automated Test

#534 test(update): fix test to not show markdowns on sidebar preview
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
Labels: Missing dev review

#533 test(update): unskip group chats tests
  tests/helpers/debugging.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/chats/EditGroup.ts
  tests/screenobjects/chats/Topbar.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/specs/reusable-accounts/11-group-chats-sidebar.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#537 test(update): copy id button to copy id and not did
  tests/helpers/debugging.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/14-create-reusable-accounts.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
Labels: Missing dev review

#539 screenobject(update): retry typing username when appium fails
  tests/screenobjects/settings/SettingsProfileScreen.ts
Labels: Missing dev review

#536 test(add): add tests for emoji suggestions
  tests/screenobjects/chats/EmojiSuggestions.ts
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#532 test(update): unskipping attachment chats tests
  tests/screenobjects/chats/ComposeAttachment.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/PinnedMessages.ts
  tests/screenobjects/chats/SendFiles.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
  tests/specs/reusable-accounts/06-chat-topbar.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#540 test(update): add more methods for emoji suggestion tests
  tests/screenobjects/chats/EmojiSuggestions.ts
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#541 screenobject(update): improving emoji and send files methods
  tests/screenobjects/chats/EmojiSuggestions.ts
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
Labels: Missing dev review

#542 test(update): fixes for changes on copy did context menu
  tests/helpers/debugging.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/EmojiSuggestions.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/14-create-reusable-accounts.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
Labels: Missing dev review

#543 test(update): increase timeout on emoji suggestions
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#544 test(update): skip emoji suggestions and fixing files indicators
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/03-files.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#545 chore(appium): pass config on shared file and set 3 mins
  config/wdio.mac.multiremote.conf.ts
  config/wdio.shared.conf.ts
  config/wdio.windows.app.conf.ts
  config/wdio.windows.ci.conf.ts
  config/wdio.windows.multiremote.conf.ts
  config/wdio.windows.onetime.conf.ts
Labels: Missing dev review
