Repository Satellite-im/testing-uplink, pull requests merged in 2023-05, with the labels that each got.

#279 chore(appium): update build steps
  .github/workflows/build-cron-job.yml
  config/wdio.mac.app.conf.ts
  config/wdio.mac.ci.conf.ts
  tests/specs/01-create-account.spec.ts
Labels: Missing dev review

#281 chore(appium): zip the exe file from windows
  .github/workflows/build-cron-job.yml
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#284 chore(appium): add remove label correctly
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review, Failed Automated Test

#285 test(update): chats refactor and add quick profile
  tests/helpers/commands.ts
  tests/screenobjects/ChatScreen.ts
  tests/screenobjects/account-creation/CreatePinScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/screenobjects/chats/ComposeAttachment.ts
  tests/screenobjects/chats/ContextMenu.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/chats/QuickProfile.ts
  tests/screenobjects/chats/ReplyPrompt.ts
  tests/screenobjects/chats/Topbar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsAboutScreen.ts
  tests/screenobjects/settings/SettingsAccessibilityScreen.ts
  tests/screenobjects/settings/SettingsAudioScreen.ts
  tests/screenobjects/settings/SettingsBaseScreen.ts
  tests/screenobjects/settings/SettingsDeveloperScreen.ts
  tests/screenobjects/settings/SettingsExtensionsScreen.ts
  tests/screenobjects/settings/SettingsFilesScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsNotificationsScreen.ts
  tests/screenobjects/settings/SettingsPrivacyScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/screenobjects/welcome-screen/WelcomeScreen.ts
  tests/specs/01-create-account.spec.ts
  tests/specs/02-chats.spec.ts
  tests/specs/03-files.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/06-settings-general.spec.ts
  tests/specs/07-settings-privacy.spec.ts
  tests/specs/08-settings-audio.spec.ts
  tests/specs/09-settings-files.spec.ts
  tests/specs/10-settings-extensions.spec.ts
  tests/specs/11-settings-notifications.spec.ts
  tests/specs/12-settings-developer.spec.ts
  tests/specs/13-settings-accessibility.spec.ts
  tests/specs/14-settings-about.spec.ts
  tests/specs/15-create-reusable-accounts.spec.ts
  tests/specs/reusable-accounts/01-chats-userA.spec.ts
  tests/specs/reusable-accounts/02-chats-userB.spec.ts
  tests/specs/reusable-accounts/03-send-several-messages-A.spec.ts
  tests/specs/reusable-accounts/04-send-several-messages-X.spec.ts
Labels: Missing dev review

#286 screenobject(update): update ui locators and methods with new aria labels
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/screenobjects/chats/ContextMenu.ts
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/chats/QuickProfile.ts
  tests/screenobjects/chats/ReplyPrompt.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/specs/03-files.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/reusable-accounts/01-chats-userA.spec.ts
  tests/specs/reusable-accounts/02-chats-userB.spec.ts
  tests/suites/02-UplinkFriends.ts
Labels: Missing dev review, Failed Automated Test

#287 test(update): skipping failing test on quick profile
  tests/specs/reusable-accounts/01-chats-userA.spec.ts
Labels: Missing dev review

#288 test(add): add tests for quick profile and refactored test suites
  config/wdio.mac.app.conf.ts
  config/wdio.mac.chatA.conf.ts
  config/wdio.mac.chatB.conf.ts
  config/wdio.mac.ci.conf.ts
  config/wdio.windows.app.conf.ts
  config/wdio.windows.chatA.conf.ts
  config/wdio.windows.ci.conf.ts
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/15-create-reusable-accounts.spec.ts
  tests/specs/reusable-accounts/ChatUserA/01-send-request-and-chat.spec.ts
  tests/specs/reusable-accounts/ChatUserA/02-quick-profile-with-A.spec.ts
  tests/specs/reusable-accounts/ChatUserB/01-accept-request-and-chat.spec.ts
  tests/specs/reusable-accounts/ChatUserB/02-quick-profile-with-B.spec.ts
  tests/specs/reusable-accounts/SendMultipleMessages/03-send-several-messages-A.spec.ts
  tests/specs/reusable-accounts/SendMultipleMessages/04-send-several-messages-X.spec.ts
  tests/suites/ChatUserA/01-ChatA.suite.ts
  tests/suites/ChatUserB/01-ChatB.suite.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkFriends.ts
  tests/suites/MainTests/03-UplinkCreateAccounts.ts
Labels: Missing dev review, Failed Automated Test

#293 test(update): fixing quick profile tests
  tests/specs/reusable-accounts/ChatUserA/02-quick-profile-with-A.spec.ts
  tests/specs/reusable-accounts/ChatUserB/02-quick-profile-with-B.spec.ts
  tests/suites/ChatUserA/01-ChatA.suite.ts
  tests/suites/ChatUserB/01-ChatB.suite.ts
Labels: Missing dev review

#297 chore(appium): update macos build instructions for makefile changes
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#294 test(add): add tests for sidebar chats
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/ContextMenuSidebar.ts
  tests/screenobjects/chats/InputBar.ts
  tests/specs/04-friends.spec.ts
  tests/specs/reusable-accounts/ChatUserA/01-send-request-and-chat.spec.ts
  tests/specs/reusable-accounts/ChatUserA/02-quick-profile-with-A.spec.ts
  tests/specs/reusable-accounts/ChatUserA/03-sidebar-with-A.spec.ts
  tests/specs/reusable-accounts/ChatUserB/01-accept-request-and-chat.spec.ts
  tests/specs/reusable-accounts/ChatUserB/02-quick-profile-with-B.spec.ts
  tests/specs/reusable-accounts/ChatUserB/03-sidebar-with-B.spec.ts
  tests/suites/ChatUserA/01-ChatA.suite.ts
  tests/suites/ChatUserB/01-ChatB.suite.ts
Labels: Missing dev review, Draft

#298 chore(suggestions): minor suggestions on read me
  README.md
Labels: Missing dev review, Failed Automated Test

#299 chore(suggestions): minor suggestions
  TEST_COVERAGE.md
Labels: Missing dev review, Failed Automated Test

#303 chore(appium): update settings tests and fix for multiremote config
  config/wdio.windows.ci.conf.ts
  config/wdio.windows.multiremote.conf.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/settings/SettingsBaseScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsNotificationsScreen.ts
  tests/specs/06-settings-general.spec.ts
  tests/specs/08-settings-audio.spec.ts
  tests/specs/10-settings-extensions.spec.ts
  tests/specs/11-settings-notifications.spec.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review
