Repository Satellite-im/testing-uplink, pull requests merged in 2023-08, with the labels that each got.

#393 test(add): tests for chats sidebar search and refactor sidebar
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/specs/02-chats.spec.ts
  tests/specs/03-files.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
Labels: Missing dev review

#394 test(update): fixing compose attachment test disappear
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
Labels: Missing dev review

#397 test(update): fixing warning error on disallowed chars
  tests/specs/01-create-account.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
Labels: Missing dev review

#395 test(add): add new tests for settings licenses and themes
  tests/screenobjects/settings/SettingsBaseScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsLicenses.ts
  tests/specs/06-settings-general.spec.ts
  tests/specs/13-settings-licenses.spec.ts
  tests/specs/14-create-reusable-accounts.spec.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review

#398 screenobject(update): fix for appium jumping input field)
  tests/screenobjects/AppScreen.ts
Labels: Missing dev review

#399 chore(appium): update settings for windows multiremote tests
  config/wdio.windows.multiremote.conf.ts
Labels: Missing dev review

#401 test(update): skipping test for typing indicator not displayed
  tests/screenobjects/files/FilesScreen.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
Labels: Missing dev review

#404 test(skip): skip group chat tests until new changes are applied
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#406 chore(typo): fix typo
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review, Failed Automated Test

#407 test(update): update warning message for not allowed chars
  tests/specs/01-create-account.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
Labels: Missing dev review

#408 chore(appium): remove windows assets artifact at success
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#409 test(update): unskip tests working after assets copied on windows
  tests/specs/06-settings-general.spec.ts
  tests/specs/08-settings-extensions.spec.ts
Labels: Missing dev review

#412 test(update): skip reactions tests and fix edit message test
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#347 chore(appium): add cucumber framework to tests
  config/wdio.mac.cucumber.conf.ts
  config/wdio.windows.cucumber.conf.ts
  package-lock.json
  package.json
  tests/features/chats/01-create-accounts-and-friends.feature
  tests/features/main/01-create-account.feature
  tests/features/main/02-chats-screen.feature
  tests/features/main/03-files.feature
  tests/features/main/05-settings-profile.feature
  tests/features/main/06-settings-general.feature
  tests/features/main/07-settings-audio.feature
  tests/features/main/08-settings-extensions.feature
  tests/features/main/09-settings-accessibility.feature
  tests/features/main/10-settings-notifications.feature
  tests/features/main/11-settings-developer.feature
  tests/features/main/12-settings-about.feature
  tests/features/main/13-friends.feature
  tests/steps/01-create-account.step.ts
  tests/steps/02-welcome-screen.step.ts
  tests/steps/03-files-screen.step.ts
  tests/steps/04-friends-screen.step.ts
  tests/steps/05-settings-profile.step.ts
  tests/steps/06-settings-general.step.ts
  tests/steps/07-settings-audio.step.ts
  tests/steps/08-settings-extensions.step.ts
  tests/steps/09-settings-accessibility.step.ts
  tests/steps/10-settings-notifications.step.ts
  tests/steps/11-settings-developer.step.ts
  tests/steps/12-settings-about.step.ts
  tests/steps/13-create-reusable-accounts.step.ts
  tests/steps/14-create-account-and-friends.step.ts
Labels: Missing dev review, Draft

#411 test(update): add emoji screenobjects and reaction tests
  tests/screenobjects/chats/ContextMenu.ts
  tests/screenobjects/chats/EmojiSelector.ts
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
Labels: Missing dev review

#413 chore(appium): copy missing assets and skip tests requiring changes
  .github/workflows/ui-automated-tests.yml
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#416 test(update): fixing sidebar and first group chat tests
  tests/screenobjects/chats/Topbar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#417 test(update): fixing group chats and edit group tests
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/EditGroup.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/specs/reusable-accounts/11-group-chats-sidebar.spec.ts
Labels: Missing dev review

#418 chore(appium): remove gherkin files not used for now
  config/wdio.mac.cucumber.conf.ts
  config/wdio.windows.cucumber.conf.ts
  tests/features/chats/01-create-accounts-and-friends.feature
  tests/features/main/01-create-account.feature
  tests/features/main/02-chats-screen.feature
  tests/features/main/03-files.feature
  tests/features/main/05-settings-profile.feature
  tests/features/main/06-settings-general.feature
  tests/features/main/07-settings-audio.feature
  tests/features/main/08-settings-extensions.feature
  tests/features/main/09-settings-accessibility.feature
  tests/features/main/10-settings-notifications.feature
  tests/features/main/11-settings-developer.feature
  tests/features/main/12-settings-about.feature
  tests/features/main/13-friends.feature
  tests/specs/reusable-accounts/SendMultipleMessages/03-send-several-messages-A.spec.ts
  tests/specs/reusable-accounts/SendMultipleMessages/04-send-several-messages-X.spec.ts
  tests/steps/01-create-account.step.ts
  tests/steps/02-welcome-screen.step.ts
  tests/steps/03-files-screen.step.ts
  tests/steps/04-friends-screen.step.ts
  tests/steps/05-settings-profile.step.ts
  tests/steps/06-settings-general.step.ts
  tests/steps/07-settings-audio.step.ts
  tests/steps/08-settings-extensions.step.ts
  tests/steps/09-settings-accessibility.step.ts
  tests/steps/10-settings-notifications.step.ts
  tests/steps/11-settings-developer.step.ts
  tests/steps/12-settings-about.step.ts
  tests/steps/13-create-reusable-accounts.step.ts
  tests/steps/14-create-account-and-friends.step.ts
Labels: Missing dev review

#419 test(update): updates to edit group chat tests
  tests/screenobjects/chats/EditGroup.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/specs/reusable-accounts/11-group-chats-sidebar.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#421 test(add): negative friend request and welcome image tests
  tests/helpers/constants.ts
  tests/specs/02-chats.spec.ts
  tests/specs/04-friends.spec.ts
Labels: Missing dev review

#422 chore(appium): update macos ci to use macos 13
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#425 test(update): updates to files favorites and emoji tests
  config/wdio.windows.app.conf.ts
  config/wdio.windows.ci.conf.ts
  tests/screenobjects/chats/ContextMenu.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/chats/FavoritesSidebar.ts
  tests/screenobjects/chats/PinnedMessages.ts
  tests/screenobjects/chats/Topbar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/specs/03-files.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/06-chat-tooltips.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/11-group-chats-sidebar.spec.ts
Labels: Missing dev review

#430 test(update): skip group chat tests failing for bug
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#435 test(update): update char counter tests after changes to app
  tests/screenobjects/chats/InputBar.ts
  tests/specs/08-settings-extensions.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
Labels: Missing dev review

#436 chore(appium): attempt retry step action on macos ci
  .github/workflows/ui-automated-tests.yml
  config/wdio.mac.ci.conf.ts
Labels: Missing dev review

#437 chore(appium): use set clipboard on windows file uploads
  tests/helpers/commands.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
Labels: Missing dev review

#434 test(update): unskip group chat tests
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/account-creation/CreatePinScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/ComposeAttachment.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/chats/EditGroup.ts
  tests/screenobjects/chats/EmojiSelector.ts
  tests/screenobjects/chats/FavoritesSidebar.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/chats/PinnedMessages.ts
  tests/screenobjects/chats/QuickProfile.ts
  tests/screenobjects/chats/ReplyPrompt.ts
  tests/screenobjects/chats/SidebarSearch.ts
  tests/screenobjects/chats/Topbar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsAboutScreen.ts
  tests/screenobjects/settings/SettingsAccessibilityScreen.ts
  tests/screenobjects/settings/SettingsAudioScreen.ts
  tests/screenobjects/settings/SettingsDeveloperScreen.ts
  tests/screenobjects/settings/SettingsExtensionsScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsLicenses.ts
  tests/screenobjects/settings/SettingsNotificationsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/screenobjects/welcome-screen/WelcomeScreen.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#438 test(add): slimbar navigation buttons and tooltips
  tests/screenobjects/chats/FavoritesSidebar.ts
  tests/specs/02-chats.spec.ts
Labels: Missing dev review
