Repository Satellite-im/testing-uplink, pull requests merged in 2023-06, with the labels that each got.

#305 update(screenobject): trying waiting for pending friends button to avoid issue
  tests/screenobjects/friends/FriendsScreen.ts
Labels: Missing dev review

#304 chore(appium): update README to include multiremote changes
  README.md
Labels: Missing dev review

#308 chore(typos): fix typos
  tests/specs/14-settings-about.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/SendMultipleMessages/03-send-several-messages-A.spec.ts
  tests/specs/reusable-accounts/SendMultipleMessages/04-send-several-messages-X.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#309 test(update): fixes for CI issues on tests
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/03-files.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
  tests/specs/reusable-accounts/07-quick-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
Labels: Missing dev review

#310 test(update): temp skipping tests that will have aria labels changed
  tests/specs/03-files.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
Labels: Missing dev review

#307 test(add): adding UI Locators for tests for group chats
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/chats/EditGroup.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/chats/ParticipantsList.ts
  tests/screenobjects/chats/ReactionPicker.ts
  tests/screenobjects/chats/ReplyPrompt.ts
  tests/screenobjects/chats/Topbar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsExtensionsScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/screenobjects/welcome-screen/WelcomeScreen.ts
  tests/specs/03-files.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review, Draft

#311 test(add): adding first tests for group chats
  tests/helpers/debugging.ts
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
  tests/specs/reusable-accounts/07-quick-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#317 test(add): add tests for participants list on group chats
  tests/screenobjects/chats/ParticipantsList.ts
  tests/screenobjects/chats/Topbar.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
Labels: Missing dev review

#319 screenobject(update): fixing issue on typing on input create chats
  tests/screenobjects/AppScreen.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
Labels: Missing dev review

#321 test(update): remove theme tests and number of participants
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/specs/06-settings-general.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
Labels: Missing dev review

#320 test(add): add tests for edit group chat
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/EditGroup.ts
  tests/screenobjects/chats/Topbar.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
  tests/suites/MainTests/01-UplinkTauri.spec.ts
Labels: Missing dev review, Draft

#322 test(update): fix for last test on edit group chats
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
Labels: Missing dev review

#323 chore(appium): remove cargo update from GH build workflow
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#324 test(add): add reaction to message tests
  tests/screenobjects/chats/MessageGroup.ts
  tests/screenobjects/chats/Messages.ts
  tests/screenobjects/chats/ReactionPicker.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#336 test(update): fixing enter input tests on windows
  .github/workflows/ui-automated-tests.yml
  tests/specs/01-create-account.spec.ts
Labels: Missing dev review

#335 test(add): add test for file size max and current indicators
  tests/specs/03-files.spec.ts
Labels: Missing dev review

#337 test(add): attempting to rename files or folders to existing names
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/specs/03-files.spec.ts
Labels: Missing dev review

#338 test(update): add small tickets tests and remove not needed files
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/settings/SettingsFilesScreen.ts
  tests/screenobjects/settings/SettingsPrivacyScreen.ts
  tests/specs/02-chats.spec.ts
  tests/specs/06-settings-general.spec.ts
  tests/specs/07-settings-audio.spec.ts
  tests/specs/07-settings-privacy.spec.ts
  tests/specs/08-settings-extensions.spec.ts
  tests/specs/09-settings-files.spec.ts
  tests/specs/09-settings-notifications.spec.ts
  tests/specs/10-settings-developer.spec.ts
  tests/specs/11-settings-accessibility.spec.ts
  tests/specs/12-settings-about.spec.ts
  tests/specs/13-create-reusable-accounts.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/suites/MainTests/01-UplinkTauri.spec.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review

#340 test(add): add reply to yourself test
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
Labels: Missing dev review, Draft

#341 chore(appium): implement retry on file spec for multiremote windows
  config/wdio.windows.multiremote.conf.ts
Labels: Missing dev review

#343 screenobject(update): changing order of elements on settings general
  tests/screenobjects/settings/SettingsGeneralScreen.ts
Labels: Missing dev review

#346 test(update): skipping and fixing chats tests than fail sometimes in CI
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
Labels: Missing dev review

#348 chore(appium): update rust toolchain to 1.70.0
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#351 chore(appium): try a fix for build windows
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review, Failed Automated Test

#352 test(update): updating sounds settings tests
  tests/screenobjects/settings/SettingsAudioScreen.ts
  tests/specs/07-settings-audio.spec.ts
Labels: Missing dev review
