Repository Satellite-im/testing-uplink, pull requests merged in 2024-01, with the labels that each got.

#582 chore(appium): refactor for chats and improve code readability
  config/wdio.mac.multiremote.conf.ts
  docs/ARIA_LABELS.md
  tests/helpers/commands.ts
  tests/helpers/debugging.ts
  tests/specs/01-create-account.spec.ts
  tests/specs/02-chats.spec.ts
  tests/specs/03-files.spec.ts
  tests/specs/04-friends.spec.ts
  tests/specs/05-settings-profile.spec.ts
  tests/specs/06-settings-general.spec.ts
  tests/specs/07-settings-audio.spec.ts
  tests/specs/08-settings-extensions.spec.ts
  tests/specs/09-settings-notifications.spec.ts
  tests/specs/10-settings-accessibility.spec.ts
  tests/specs/11-settings-about.spec.ts
  tests/specs/12-settings-licenses.spec.ts
  tests/specs/13-settings-developer.spec.ts
  tests/specs/14-create-reusable-accounts.spec.ts
  tests/specs/15-settings-messages.spec.ts
  tests/specs/reusable-accounts/01-create-accounts-and-friends.spec.ts
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
  tests/specs/reusable-accounts/06-chat-topbar.spec.ts
  tests/specs/reusable-accounts/07-quick-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/09-group-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/specs/reusable-accounts/11-group-chats-sidebar.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
  tests/suites/Chats/02-Empty.suite.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review

#585 test(add): add tests to bypass recovery seed screens
  tests/helpers/commands.ts
  tests/screenobjects/account-creation/CreateOrImportScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/account-creation/EnterRecoverySeedScreen.ts
  tests/screenobjects/account-creation/SaveRecoverySeedScreen.ts
  tests/specs/01-create-account.spec.ts
Labels: Missing dev review

#584 chore(appium): restore friends tests
  tests/fixtures/users/FriendsTestUser/.user/state.json
  tests/fixtures/users/FriendsTestUser/.user/warp/.cache_id_v0
  tests/fixtures/users/FriendsTestUser/.user/warp/.id
  tests/fixtures/users/FriendsTestUser/.user/warp/.request_queue
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/2e/bafyreid7udnt2wvyma6uk2hdgxafp7zi3eusdaozeuisa3zoaygw6wu2em.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/2i/bafyreia6fugejce4uhhy2kim6v7go2acnh4mvf2qwgeqhdt2pn62xwp2iu.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/5u/bafyreih2csqsxz334sv7bn4r6pizp3hfgcl3ii4mgx653km2yvpkzdk5ue.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/6m/bafyreidyrinyh3n2pxv2lotsukdwmjtyz3n7apxr7ocdauxakwvxfgs6mq.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/6o/bafyreievcoau64kszkgclyefn4qa33by5lrb4xfhk46wi5fn22qnnbt6ou.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/cs/bafybeie25zc4egn6rts5nf7mcfmw2aw42pandzggi3w5jvv45ecazkbcsq.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/ef/bafyreiawoiqb75pg6u3c6qgf3cafarpj7cbbv3rukmqpj33lv5vwovtefa.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/fb/bafyreig7asv3i5club3earxpdgbk6shhu4cumawxpq7jio376gspquofb4.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/fm/bafyreierhg7jbmtzk5orqz22lhevskvggzmkiiadeazwizfdscclmykfmy.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/hh/bafyreidkriynppmqqkb35ni3r66tanlrdskq26tfaj4clpj2ajxominhhq.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/lr/bafyreidp25levhpht5ahyrig2moyaysdcdk7s3kddtwzfc6cmkwdkawlrq.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/ma/bafyreigdxbgqxqqeap7id2jizr2o6tg2mcv53xlkf23brdz7mbrwongmam.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/mo/bafyreidwx2fvfdiaox32v2mnn6sxu3j4qoxeqcuenhtgrv5qv6litfnmoe.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/mo/bafyreihguitm4ss6qbg3c6mtmtdnuesczo3wpplgxixrp3ruyabzljgmoa.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/r6/bafyreidl3pb25obujy6sz4dee7ea4us47blyyonj7t5pimmuy6hbtzrr6y.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/s3/bafyreihwqrevbokkikp4f5qgqwbcngromvu2sjxrhypjbmk6owxqqoks3i.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/vp/bafyreihizx7aromxrfocmrb5avxdqumevbezxbzs6fqbrvsbsvxhutevpu.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/wz/bafyreihskc4bkdlcibequ73v3n542vgdj46mlgrzux3zy6jvoaoj7utwzm.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/x4/bafyreiehh5c2pbemb47evw4x57upqjvtzcnlexjdxeda6ccvbxlns63x4u.data
  tests/fixtures/users/FriendsTestUser/.user/warp/blockstore/yh/bafyreigm6tdd6lszhagelzknjosf5jm6rpsrcdbqp6lmi2p2rvlbq45yhi.data
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/2i/afyreia6fugejce4uhhy2kim6v7go2acnh4mvf2qwgeqhdt2pn62xwp2iu.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/5u/afyreih2csqsxz334sv7bn4r6pizp3hfgcl3ii4mgx653km2yvpkzdk5ue.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/6m/afyreidyrinyh3n2pxv2lotsukdwmjtyz3n7apxr7ocdauxakwvxfgs6mq.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/6o/afyreievcoau64kszkgclyefn4qa33by5lrb4xfhk46wi5fn22qnnbt6ou.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/ef/afyreiawoiqb75pg6u3c6qgf3cafarpj7cbbv3rukmqpj33lv5vwovtefa.recursive
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/fb/afyreig7asv3i5club3earxpdgbk6shhu4cumawxpq7jio376gspquofb4.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/fm/afyreierhg7jbmtzk5orqz22lhevskvggzmkiiadeazwizfdscclmykfmy.recursive
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/lr/afyreidp25levhpht5ahyrig2moyaysdcdk7s3kddtwzfc6cmkwdkawlrq.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/ma/afyreigdxbgqxqqeap7id2jizr2o6tg2mcv53xlkf23brdz7mbrwongmam.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/mo/afyreihguitm4ss6qbg3c6mtmtdnuesczo3wpplgxixrp3ruyabzljgmoa.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/r6/afyreidl3pb25obujy6sz4dee7ea4us47blyyonj7t5pimmuy6hbtzrr6y.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/s3/afyreihwqrevbokkikp4f5qgqwbcngromvu2sjxrhypjbmk6owxqqoks3i.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/vp/afyreihizx7aromxrfocmrb5avxdqumevbezxbzs6fqbrvsbsvxhutevpu.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/x4/afyreiehh5c2pbemb47evw4x57upqjvtzcnlexjdxeda6ccvbxlns63x4u.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/datastore/pins/yh/afyreigm6tdd6lszhagelzknjosf5jm6rpsrcdbqp6lmi2p2rvlbq45yhi.direct
  tests/fixtures/users/FriendsTestUser/.user/warp/fake_tesseract.json
  tests/fixtures/users/FriendsTestUser/.user/warp/repo_lock
  tests/fixtures/users/FriendsTestUser/.user/warp/tesseract.json
  tests/helpers/commands.ts
  tests/helpers/constants.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/04-friends.spec.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
Labels: Missing dev review

#587 chore(appium): get current driver from env variable
  package.json
  scripts/windows_app.ps1
  scripts/windows_ci.ps1
  tests/helpers/commands.ts
  tests/screenobjects/AppScreen.ts
  tests/screenobjects/UplinkMainScreen.ts
  tests/screenobjects/account-creation/CreateOrImportScreen.ts
  tests/screenobjects/account-creation/CreatePinScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/account-creation/EnterRecoverySeedScreen.ts
  tests/screenobjects/account-creation/SaveRecoverySeedScreen.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/screenobjects/chats/ChatsSidebar.ts
  tests/screenobjects/chats/ComposeAttachment.ts
  tests/screenobjects/chats/ContextMenu.ts
  tests/screenobjects/chats/ContextMenuSidebar.ts
  tests/screenobjects/chats/CreateGroupChat.ts
  tests/screenobjects/chats/EditGroup.ts
  tests/screenobjects/chats/EmojiSelector.ts
  tests/screenobjects/chats/EmojiSuggestions.ts
  tests/screenobjects/chats/FavoritesSidebar.ts
  tests/screenobjects/chats/ImagePreview.ts
  tests/screenobjects/chats/InputBar.ts
  tests/screenobjects/chats/MessageGroupLocal.ts
  tests/screenobjects/chats/MessageGroupRemote.ts
  tests/screenobjects/chats/MessageLocal.ts
  tests/screenobjects/chats/MessageRemote.ts
  tests/screenobjects/chats/OutgoingCallModal.ts
  tests/screenobjects/chats/PinnedMessages.ts
  tests/screenobjects/chats/QuickProfile.ts
  tests/screenobjects/chats/ReplyPrompt.ts
  tests/screenobjects/chats/SendFiles.ts
  tests/screenobjects/chats/ShareDid.ts
  tests/screenobjects/chats/SidebarSearch.ts
  tests/screenobjects/chats/Topbar.ts
  tests/screenobjects/files/FilesScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/screenobjects/settings/CropToolProfileModal.ts
  tests/screenobjects/settings/SettingsAboutScreen.ts
  tests/screenobjects/settings/SettingsAccessibilityScreen.ts
  tests/screenobjects/settings/SettingsAudioScreen.ts
  tests/screenobjects/settings/SettingsBaseScreen.ts
  tests/screenobjects/settings/SettingsDeveloperScreen.ts
  tests/screenobjects/settings/SettingsExtensionsScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsLicenses.ts
  tests/screenobjects/settings/SettingsMessagesScreen.ts
  tests/screenobjects/settings/SettingsNotificationsScreen.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/screenobjects/welcome-screen/WelcomeScreen.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#588 screenobject(update): add new aria labels for settings and seed words
  tests/screenobjects/account-creation/CreateOrImportScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/account-creation/EnterRecoverySeedScreen.ts
  tests/screenobjects/account-creation/SaveRecoverySeedScreen.ts
  tests/screenobjects/settings/SettingsAboutScreen.ts
  tests/screenobjects/settings/SettingsAccessibilityScreen.ts
  tests/screenobjects/settings/SettingsAudioScreen.ts
  tests/screenobjects/settings/SettingsDeveloperScreen.ts
  tests/screenobjects/settings/SettingsExtensionsScreen.ts
  tests/screenobjects/settings/SettingsGeneralScreen.ts
  tests/screenobjects/settings/SettingsLicenses.ts
  tests/screenobjects/settings/SettingsMessagesScreen.ts
  tests/screenobjects/settings/SettingsNotificationsScreen.ts
Labels: Missing dev review

#589 test(add): add test for scroll to bottom button
  tests/helpers/commands.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/specs/reusable-accounts/05-message-attachments.spec.ts
Labels: Missing dev review

#590 test(update): fixing edit group and sidebar group tests
  tests/specs/reusable-accounts/03-message-context-menu.spec.ts
  tests/specs/reusable-accounts/07-quick-profile.spec.ts
  tests/specs/reusable-accounts/08-sidebar-chats.spec.ts
  tests/specs/reusable-accounts/10-group-chats-edit.spec.ts
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review

#591 test(add): refactor tests for creating account
  tests/screenobjects/account-creation/CreateOrImportScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/account-creation/SaveRecoverySeedScreen.ts
  tests/screenobjects/chats/ChatsLayout.ts
  tests/specs/01-create-account.spec.ts
Labels: Missing dev review

#592 test(update): fixing chat test for links
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#593 test(update): improvements for chat input tests on links
  tests/screenobjects/chats/MessageLocal.ts
  tests/screenobjects/chats/MessageRemote.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#594 test(add): add test for import account screen
  config/wdio.windows.app.conf.ts
  config/wdio.windows.ci.conf.ts
  tests/helpers/commands.ts
  tests/screenobjects/account-creation/CreateOrImportScreen.ts
  tests/screenobjects/account-creation/CreatePinScreen.ts
  tests/screenobjects/account-creation/CreateUserScreen.ts
  tests/screenobjects/account-creation/EnterRecoverySeedScreen.ts
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/01-create-account.spec.ts
  tests/specs/16-import-account.spec.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review, Draft

#597 test(assertions): update copy
  tests/specs/03-files.spec.ts
Labels: Missing dev review

#596 test(add): change status and reveal seed on settings profile
  tests/screenobjects/settings/RemoveSeedPhraseModal.ts
  tests/screenobjects/settings/SettingsProfileScreen.ts
Labels: Missing dev review

#607 test(add): add tests for settings profile status and reveal recovery
  tests/screenobjects/settings/SettingsProfileScreen.ts
  tests/specs/05-settings-profile.spec.ts
Labels: Missing dev review

#595 chore(appium): execute friends tests on windows
  package.json
  tests/screenobjects/friends/FriendsScreen.ts
  tests/specs/04-friends.spec.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review

#608 test(add): add test for offline friend requests
  tests/helpers/commands.ts
  tests/specs/17-offline-requests.spec.ts
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review

#610 chore(appium): update suites files
  tests/suites/MainTests/01-UplinkTests.suite.ts
  tests/suites/MainTests/02-UplinkWindows.suite.ts
Labels: Missing dev review

#606 screenobject(update): update ui locators for uplink markdowns pr
  .github/workflows/ui-automated-tests.yml
  tests/screenobjects/chats/InputBar.ts
  tests/specs/reusable-accounts/04-message-input.spec.ts
Labels: Missing dev review

#612 chore(appium): removing ref to unexisting branch
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#613 test(update): remove assertion on emojis
  tests/specs/11-settings-about.spec.ts
Labels: Missing dev review

#611 chore(appium): spawn CI instance of Warp for offline tests
  .github/workflows/ui-automated-tests.yml
  package.json
  scripts/replace_node.ps1
  scripts/replace_node.sh
  scripts/windows_app.ps1
  scripts/windows_ci.ps1
Labels: Missing dev review, Failed Automated Test

#617 chore(appium): run CI macos tests on macos 14
  .github/workflows/ui-automated-tests.yml
Labels: Missing dev review

#618 test(update): skip edit group chat tests for bugs
  tests/suites/Chats/01-Chats.suite.ts
Labels: Missing dev review, Failed Automated Test

#619 test(update): fix reply messages issue on chats tests
  tests/specs/reusable-accounts/02-chat-replies.spec.ts
Labels: Missing dev review
